# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
     git:
        repo: "puppetlabs/git"
        ref: "0.5.0"
     remote_file:
        repo: "lwf/remote_file"
        ref: "1.1.3"
     stdlib:
        repo: "puppetlabs/stdlib"
        ref: "4.25.1"
     vcsrepo:
        repo: "puppetlabs/vcsrepo"
        ref: "2.4.0"
